-- Deploy My-Journey:forum to pg
BEGIN;

CREATE TABLE "rubric" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "topic" TEXT NOT NULL,
    "creation_date" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE "likes" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "username" TEXT NOT NULL UNIQUE,
    "user_id" INT NOT NULL REFERENCES "user"("id")
);

CREATE TABLE "message" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "title" TEXT NOT NULL UNIQUE,
    "content" TEXT NOT NULL UNIQUE,
    "publication_date" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "likes" TEXT UNIQUE,
    "user_id" INT NOT NULL REFERENCES "user"("id"),
    "rubric_id" INT NOT NULL REFERENCES "rubric"("id"),
    "likes_id" INT NOT NULL REFERENCES "likes"("id")
);

CREATE TABLE "session" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "username" TEXT NOT NULL UNIQUE,
    "token" TEXT NOT NULL UNIQUE,
    "user_id" INT NOT NULL REFERENCES "user"("id")
);

COMMIT;