-- Deploy My-Journey:my-journey-v1 to pg
BEGIN;

CREATE TABLE "question" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "question" TEXT NOT NULL
);

CREATE TABLE "response" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "response" JSON NOT NULL,
    "question_id" INT NOT NULL REFERENCES "question"("id")
);

CREATE TABLE "destination" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "city_name" TEXT NOT NULL,
    "country" TEXT NOT NULL,
    "city_code" TEXT NOT NULL,
    "country_code" TEXT NOT NULL,
    "continent" TEXT NOT NULL,
    "latitude" TEXT NOT NULL,
    "longitude" TEXT NOT NULL,
    "landscape" TEXT ARRAY NOT NULL,
    "season" TEXT ARRAY NOT NULL,
    "budget" TEXT ARRAY NOT NULL,
    "history" TEXT NOT NULL,
    "destination_visual" TEXT NOT NULL
);

CREATE TABLE "user" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "username" TEXT NOT NULL UNIQUE,
    "firstname" TEXT,
    "lastname" TEXT,
    "email" TEXT NOT NULL UNIQUE,
    "password" TEXT NOT NULL,
    "role" TEXT DEFAULT 'Traveller',
    "avatar" TEXT
);

CREATE TABLE "journey" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "destination_result" TEXT NOT NULL,
    "user_id" INT NOT NULL REFERENCES "user"("id")
);

CREATE TABLE "register" (
    "destination_id" INT NOT NULL REFERENCES "destination"("id"),
    "journey_id" INT NOT NULL REFERENCES "journey"("id")
);

CREATE TABLE "favoris" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "type" TEXT NOT NULL,
    "href" TEXT NOT NULL,
    "user_id" INT NOT NULL REFERENCES "user"("id")
);

CREATE TABLE "review" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "href" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "username" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "rating" TEXT NOT NULL,
    "user_id" INT NOT NULL REFERENCES "user"("id")
);

COMMIT;
